# Module NumPy 
### Numerical Python: package for scientific computing 
https://numpy.org/ 
#### Features:
* Multi dimensional array
* Element by element operations
* Mathematical operations like linear algebra
* Method for procession arrays

In [1]:
!pip install numpy

In [5]:
import numpy as np
a = np.array([1,2,3])
print(a, type(a))
print(a.dtype)

[1 2 3] <class 'numpy.ndarray'>
int64


In [6]:
b = np.array([1,2,3,'4'])
print(b, type(b))
print(b.dtype)

['1' '2' '3' '4'] <class 'numpy.ndarray'>
<U21


In [8]:
c=np.arange(10,20)
print(c, type(c))

# Check dimention
print('No of dimention: ',c.ndim)

[10 11 12 13 14 15 16 17 18 19] <class 'numpy.ndarray'>
No of dimention:  1


In [1]:
import numpy as np

# Define the array
d = np.array([[10, 20, 30, 100], [40, 50, 60, 110], [70, 80, 90, 120]])

# Print the array and its type
print(d, type(d))

# Check dimension
print('Number of dimensions: ', d.ndim)
print('Shape: ', d.shape)  # Rows come first
print('Size: ', d.size)    # Total number of elements

# Get size of each element in bytes
print('Size of each element (in bytes): ', d.itemsize)


[[ 10  20  30 100]
 [ 40  50  60 110]
 [ 70  80  90 120]] <class 'numpy.ndarray'>
Number of dimensions:  2
Shape:  (3, 4)
Size:  12
Size of each element (in bytes):  8


In [3]:
#Indexing 2D array
d[2][1]

np.int64(80)

In [5]:
for i in d:
    print(i)

[ 10  20  30 100]
[ 40  50  60 110]
[ 70  80  90 120]


In [7]:
#nditer nd iter 
# nditer = n dimesional iteration to iterate all elements in the array
for i in np.nditer(d):
    print(i)

10
20
30
100
40
50
60
110
70
80
90
120


In [13]:
# Matrix multiplication
A=[[1,2,3],[4,5,6]]
B=[[10,11],[20,21],[30,31]]
C=np.dot(A,B)
print(C,'\n')
D=np.dot(B,A)
print(D)

[[140 146]
 [320 335]] 

[[ 54  75  96]
 [104 145 186]
 [154 215 276]]


In [37]:
#Import data from a file 
# a specific column 
# default read is float  --> int32
data = np.loadtxt('marks.csv',delimiter=',',usecols=(5),skiprows=1)
print(data.shape, data.ndim, data.size, data.itemsize,type(data))
data = np.loadtxt('marks.csv',delimiter=',',usecols=(5),skiprows=1,dtype='int32')
print(data.shape, data.ndim, data.size, data.itemsize,type(data))
print(data)
print('Total Marks: ', data.sum())
print('Average Marks: ', data.mean())
print('Max Marks: ', data.max())
print('Min Marks: ', data.min())
print('Standard Deviation: ', data.std())
print('variance Marks: ', data.var())


(130,) 1 130 8 <class 'numpy.ndarray'>
(130,) 1 130 4 <class 'numpy.ndarray'>
[420 280 350 269 317 470 333 365 305 350 460 474 409 377 415 382 298 462
 370 313 464 302 252 259 308 392 424 403 370 328 398 434 291 472 263 439
 464 449 401 364 296 292 438 357 331 317 429 407 321 274 447 274 437 411
 257 310 396 270 311 459 378 316 283 266 381 409 313 306 448 348 292 400
 352 441 428 309 441 439 264 281 302 432 423 336 383 321 469 270 341 281
 403 333 323 348 345 397 449 261 456 370 322 379 446 404 301 254 351 444
 264 286 463 273 316 324 465 398 324 340 414 346 408 332 394 474 398 262
 410 391 444 461]
Total Marks:  47356
Average Marks:  364.2769230769231
Max Marks:  474
Min Marks:  252
Standard Deviation:  66.17947803971762
variance Marks:  4379.723313609467


In [ ]:
#Pandas --> data analysis & manipulation tool 
# --> works with structured data 
# ML Machine Learning: Fetch data, prepocess, ETL, clean, manipulate, ... to the ML machine 
# 40% work done in Pandas

# Data Structures Panel Data in Pandas 
# DataFrame --> Table 
# Data Series --> Column

#Raw data --> Data Frame --> (merge, clean ...)--> Processed Data --> ML 

import pandas as pd  

